import { useEffect, useState } from 'react'
import type { Customer, CustomerDetail } from '../api/types'
import { api } from '../api/client'
import { Drawer, Empty, Loading, SectionHead, Status, dt, label, money } from '../components/UI'

export function CustomersView({items,reload}:{items:Customer[];reload:(search?:string)=>Promise<void>}){
 const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Customer|null>(null); const [detail,setDetail]=useState<CustomerDetail|null>(null)
 useEffect(()=>{const t=setTimeout(()=>{void reload(search)},280);return()=>clearTimeout(t)},[search])
 const open=async(c:Customer)=>{setSelected(c);setDetail(null);setDetail(await api.customer(c.id))}
 return <div className="page-stack"><SectionHead title="Customers" subtitle="One timeline from ad click to repeat buyer." action={<div className="searchbox"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, username or Telegram ID"/></div>}/>
 {!items.length?<Empty title="No customers found"/>:<div className="customer-grid">{items.map(c=><button className="customer-card" onClick={()=>void open(c)} key={c.id}><div className="customer-card__top"><div className="avatar avatar--lg">{(c.first_name||'?')[0]}</div><div><h3>{c.first_name} {c.last_name||''}</h3><span>{c.username?`@${c.username}`:`TG ${c.telegram_id}`}</span></div><Status value={c.customer_stage}/></div><div className="customer-metrics"><div><span>Intent</span><b>{c.max_intent_score}</b></div><div><span>Owned</span><b>{c.products_owned}</b></div><div><span>Value</span><b>{money(c.lifetime_value_br)}</b></div></div><div className="customer-foot"><span>{label(c.role)}</span><span>Seen {dt(c.last_seen_at)}</span></div></button>)}</div>}
 {selected&&<Drawer title={selected.first_name} onClose={()=>{setSelected(null);setDetail(null)}}>{!detail?<Loading/>:<div className="detail-stack"><div className="profile-hero"><div className="avatar avatar--xl">{(selected.first_name||'?')[0]}</div><div><h2>{selected.first_name} {selected.last_name||''}</h2><p>{selected.username?`@${selected.username}`:`Telegram ${selected.telegram_id}`}</p></div></div><div className="detail-grid"><div><span>Stage</span><b>{label(String(detail.user.customer_stage))}</b></div><div><span>Language</span><b>{String(detail.user.preferred_language||'—').toUpperCase()}</b></div><div><span>Role</span><b>{label(String(detail.user.role||'—'))}</b></div><div><span>AI status</span><b>{label(String(detail.user.ai_experience||'—'))}</b></div><div><span>Goal</span><b>{label(String(detail.user.main_goal||'—'))}</b></div><div><span>Obstacle</span><b>{label(String(detail.user.main_obstacle||'—'))}</b></div></div>{detail.source&&<div className="detail-section"><h4>First source</h4><p>{String(detail.source.creative||detail.source.campaign||detail.source.platform||detail.source.source||'Direct')} {detail.source.angle?`· ${detail.source.angle}`:''}</p></div>}{detail.referral&&<div className="detail-section"><h4>Referral</h4><p>{String(detail.referral.referrer_username?`@${detail.referral.referrer_username}`:detail.referral.referrer_name||'Referred')}</p></div>}<div className="detail-section"><h4>Product journeys</h4>{detail.journeys.length?detail.journeys.map((j,i)=><div className="timeline-row" key={i}><i/><div><b>{String(j.product_title||'Product')}</b><span>{label(String(j.stage||''))} · Intent {String(j.intent_score||0)}</span></div></div>):<p className="muted-copy">No product journey yet.</p>}</div><div className="detail-section"><h4>Recent activity</h4>{detail.events.slice(0,16).map((e,i)=><div className="timeline-row" key={i}><i/><div><b>{label(String(e.event_type||''))}</b><span>{dt(String(e.occurred_at||''))}</span></div></div>)}</div></div>}</Drawer>}
 </div>
}
