import { useState } from 'react'
import type { FinancialDashboard } from '../api/types'
import { api } from '../api/client'
import { Kpi, Modal, SectionHead, money, dt, label } from '../components/UI'
import { Sparkline } from '../components/Sparkline'

export function FinancialsView({data,reload}:{data:FinancialDashboard;reload:()=>void}){
  const [open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState('')
  const [form,setForm]=useState({expense_date:new Date().toISOString().slice(0,10),category:'ads',amount_br:'',description:'',reference:''})
  const save=async()=>{setBusy(true);setErr('');try{await api.createExpense({...form,amount_br:Number(form.amount_br)});setOpen(false);setForm({...form,amount_br:'',description:'',reference:''});reload()}catch(e){setErr(e instanceof Error?e.message:'Could not save expense')}finally{setBusy(false)}}
  const remove=async(id:string)=>{if(!confirm('Delete this recorded expense?'))return;try{await api.deleteExpense(id);reload()}catch(e){alert(e instanceof Error?e.message:'Could not delete expense')}}
  return <div className="page-stack final-page"><div className="hero-head"><div><p className="eyebrow">MONEY · {data.days} DAYS</p><h1>Financials</h1><p>Operational cash visibility — not a replacement for formal accounting.</p></div><button className="btn btn--green" onClick={()=>setOpen(true)}>+ Record expense</button></div>
    <section className="kpi-grid"><Kpi eyebrow="Gross revenue" value={money(data.summary.gross_revenue_br)} note={`${data.summary.sales} paid sales`} icon="wallet"/><Kpi eyebrow="Recorded expenses" value={money(data.summary.recorded_expenses_br)} note="Dashboard-entered costs" icon="financials"/><Kpi eyebrow="Paid commissions" value={money(data.summary.paid_commissions_br)} note={`${money(data.summary.commission_owed_br)} still owed`} icon="payments"/><Kpi eyebrow="Net cash view" value={money(data.summary.net_cash_br)} note="Revenue − refunds − costs − paid commissions" icon="pulse"/></section>
    <section className="dashboard-grid"><article className="panel"><SectionHead title="Cash movement" subtitle="Daily paid revenue"/><Sparkline values={data.daily.map(x=>Number(x.revenue_br||0))}/><div className="split-legend"><div><i className="dot dot--green"/><span>Full-price revenue</span><strong>{money(data.summary.full_price_revenue_br)}</strong></div><div><i className="dot dot--muted"/><span>Discount revenue</span><strong>{money(data.summary.discounted_revenue_br)}</strong></div></div></article><article className="panel"><SectionHead title="Payment methods" subtitle="Approved payments in this window"/><div className="audience-list">{data.payment_methods.map(x=><div key={x.payment_method}><span>{label(x.payment_method)}</span><b>{x.payments} payments</b><strong>{money(x.amount_br)}</strong></div>)}</div></article></section>
    <article className="panel"><SectionHead title="Recorded expenses" subtitle="Every change is audit logged"/><div className="table-scroll"><table><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Recorded by</th><th/></tr></thead><tbody>{data.expenses.map(x=><tr key={x.id}><td>{new Date(x.expense_date+'T00:00:00').toLocaleDateString()}</td><td>{label(x.category)}</td><td><strong>{x.description}</strong><span>{x.reference||'—'}</span></td><td>{money(x.amount_br)}</td><td>{x.created_by||'—'}<span>{dt(x.created_at)}</span></td><td><button className="btn btn--danger-quiet" onClick={()=>void remove(x.id)}>Delete</button></td></tr>)}</tbody></table></div></article>
    {open&&<Modal title="Record business expense" onClose={()=>setOpen(false)}><div className="editor-form"><div className="form-grid"><label>Date<input className="field" type="date" value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></label><label>Category<select className="field" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="ads">Ads</option><option value="software">Software</option><option value="contractor">Contractor</option><option value="bank_fee">Bank fee</option><option value="refund_cost">Refund cost</option><option value="operations">Operations</option><option value="other">Other</option></select></label><label>Amount (Br)<input className="field" type="number" min="0.01" step="0.01" value={form.amount_br} onChange={e=>setForm({...form,amount_br:e.target.value})}/></label><label>Reference<input className="field" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="span-2">Description<textarea className="field textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div>{err&&<p className="form-error">{err}</p>}<div className="modal-actions"><button className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn--green" disabled={busy||!form.amount_br||!form.description.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save expense'}</button></div></div></Modal>}
  </div>
}
