import { useEffect, useMemo, useState } from 'react'
import { api } from '../api/client'
import type { Automation, Broadcast, DiscountRule, MarketingDashboard, MarketingProduct, ReferralPartner } from '../api/types'
import { Icon } from '../components/Icon'
import { Empty, Kpi, Modal, SectionHead, Status, dt, money } from '../components/UI'

type Tab='broadcasts'|'automations'|'discounts'|'referrals'|'links'
const tabs:Array<{id:Tab;label:string}>=[
  {id:'broadcasts',label:'Broadcasts'},{id:'automations',label:'Automations'},{id:'discounts',label:'Discounts'},
  {id:'referrals',label:'Referrals'},{id:'links',label:'Ad Links'},
]

const audienceOptions=[
 ['everyone','Everyone'],['non_buyers','Non-buyers'],['customers','Customers'],['product_buyers','Product buyers'],
 ['full_price_buyers','Full-price buyers'],['discount_buyers','Discount buyers'],['referral_partners','Referral partners'],
 ['rejected_payment','Rejected payment'],['high_intent','High-intent prospects'],['custom','Custom'],
] as const

const productRequired=(kind:string)=>['product_buyers','full_price_buyers','discount_buyers','high_intent'].includes(kind)
const asObj=(v:unknown):Record<string,unknown>=>typeof v==='object'&&v!==null?v as Record<string,unknown>:{}
const asString=(v:unknown)=>typeof v==='string'?v:''

function ProductSelect({products,value,onChange,required=false,disabled=false}:{products:MarketingProduct[];value:string;onChange:(v:string)=>void;required?:boolean;disabled?:boolean}){
 return <select className="field" value={value} onChange={e=>onChange(e.target.value)} required={required} disabled={disabled}><option value="">{required?'Choose product…':'All products'}</option>{products.map(p=><option value={p.id} key={p.id}>{p.title} · {p.status}</option>)}</select>
}

function AudienceFields({products,kind,setKind,language,setLanguage,product,setProduct,score,setScore}:{products:MarketingProduct[];kind:string;setKind:(v:string)=>void;language:string;setLanguage:(v:string)=>void;product:string;setProduct:(v:string)=>void;score:string;setScore:(v:string)=>void}){
 return <div className="marketing-form-grid"><label>Audience<select className="field" value={kind} onChange={e=>setKind(e.target.value)}>{audienceOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Language<select className="field" value={language} onChange={e=>setLanguage(e.target.value)}><option value="">Any language</option><option value="am">Amharic</option><option value="en">English</option></select></label><label>Product<ProductSelect products={products} value={product} onChange={setProduct} required={productRequired(kind)}/></label><label>Minimum intent score<input className="field" type="number" min="0" max="1000" value={score} onChange={e=>setScore(e.target.value)} placeholder="Optional"/></label></div>
}

function BroadcastEditor({products,existing,onClose,onDone}:{products:MarketingProduct[];existing?:Broadcast;onClose:()=>void;onDone:()=>Promise<void>}){
 const aud=asObj(existing?.audience_definition);const am=asObj(existing?.content_am);const en=asObj(existing?.content_en)
 const amButtons=Array.isArray(am.buttons)?am.buttons as Array<Record<string,unknown>>:[];const enButtons=Array.isArray(en.buttons)?en.buttons as Array<Record<string,unknown>>:[]
 const [name,setName]=useState(existing?.name||'');const[kind,setKind]=useState(asString(aud.kind)||'non_buyers');const[language,setLanguage]=useState(asString(aud.language));const[product,setProduct]=useState(asString(aud.product_id));const[score,setScore]=useState(String(aud.minimum_intent_score??''));
 const[amText,setAmText]=useState(asString(am.text));const[enText,setEnText]=useState(asString(en.text));const[buttonText,setButtonText]=useState(asString(amButtons[0]?.text)||asString(enButtons[0]?.text)||'🛍 Open Zemen');const[buttonUrl,setButtonUrl]=useState(asString(amButtons[0]?.url)||asString(enButtons[0]?.url));
 const[media,setMedia]=useState<Record<string,string>|null>(()=>{const m=asObj(am.media||en.media);return m.file_id?{type:asString(m.type),file_id:asString(m.file_id)}:null});const[schedule,setSchedule]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[count,setCount]=useState<number|null>(null)
 const audience=()=>({kind,language:language||null,product_id:product||null,minimum_intent_score:score?Number(score):null})
 const content=(text:string)=>text.trim()||media?{text:text.trim(),media,buttons:buttonText.trim()&&buttonUrl.trim()?[{key:'primary',text:buttonText.trim(),url:buttonUrl.trim()}]:[]}:null
 const save=async()=>{setBusy(true);setError('');try{const payload={name,audience_definition:audience(),content_am:content(amText),content_en:content(enText),attribution_window_hours:168,...(existing?{expected_revision:existing.revision}:{})};const r=existing?await api.updateBroadcast(existing.id,payload):await api.createBroadcast(payload) as {id?:string};await onDone();if(!existing&&r&&typeof r==='object'&&'id'in r&&r.id){/* stay for scheduling? */}onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save broadcast')}finally{setBusy(false)}}
 const saveAndSend=async()=>{setBusy(true);setError('');try{let id=existing?.id;let revision=existing?.revision;const payload={name,audience_definition:audience(),content_am:content(amText),content_en:content(enText),attribution_window_hours:168,...(existing?{expected_revision:revision}:{})};const r=(existing?await api.updateBroadcast(existing.id,payload):await api.createBroadcast(payload)) as {id:string};id=r.id||id;if(!id)throw new Error('Broadcast ID missing');await api.scheduleBroadcast(id,schedule?new Date(schedule).toISOString():null);await onDone();onClose()}catch(e){setError(e instanceof Error?e.message:'Could not schedule broadcast')}finally{setBusy(false)}}
 const preview=async()=>{try{setCount((await api.audienceCount(audience())).count)}catch(e){setError(e instanceof Error?e.message:'Could not count audience')}}
 const upload=async(file:File|null)=>{if(!file)return;setBusy(true);try{const f=new FormData();f.append('file',file);setMedia(await api.uploadBroadcastMedia(f))}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 return <Modal title={existing?'Edit broadcast':'New broadcast'} onClose={onClose}><div className="marketing-editor"><label>Internal name<input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="A03 non-buyer follow-up"/></label><AudienceFields products={products} kind={kind} setKind={setKind} language={language} setLanguage={setLanguage} product={product} setProduct={setProduct} score={score} setScore={setScore}/><div className="audience-preview"><button className="btn" onClick={()=>void preview()}>Preview audience</button><span>{count===null?'Count before sending':`${count.toLocaleString()} reachable users`}</span></div><div className="language-copy-grid"><label>🇪🇹 Amharic<textarea className="field textarea textarea--lg" value={amText} onChange={e=>setAmText(e.target.value)} placeholder="Message…"/></label><label>🇬🇧 English<textarea className="field textarea textarea--lg" value={enText} onChange={e=>setEnText(e.target.value)} placeholder="Message…"/></label></div><div className="marketing-form-grid"><label>Button label<input className="field" value={buttonText} onChange={e=>setButtonText(e.target.value)}/></label><label>Button destination<input className="field" value={buttonUrl} onChange={e=>setButtonUrl(e.target.value)} placeholder="https://t.me/..."/></label><label>Schedule<input className="field" type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)}/></label><label className="broadcast-upload">Media{media?<span>✓ {media.type}</span>:<span>Optional</span>}<input type="file" hidden onChange={e=>void upload(e.target.files?.[0]||null)}/><button className="btn" type="button" onClick={e=>(e.currentTarget.parentElement?.querySelector('input') as HTMLInputElement|null)?.click()}>Upload media</button></label></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="btn" onClick={()=>void save()} disabled={busy}>{busy?'Working…':'Save draft'}</button><button className="btn btn--green" onClick={()=>void saveAndSend()} disabled={busy}>{schedule?'Schedule broadcast':'Send now'}</button></div></div></Modal>
}

function Broadcasts({data,reload}:{data:MarketingDashboard;reload:()=>Promise<void>}){const[open,setOpen]=useState<Broadcast|boolean>(false);return <div className="marketing-pane"><SectionHead title="Broadcast Studio" subtitle="Choose the audience, write once, preview the reach and send without touching code." action={<button className="btn btn--green" onClick={()=>setOpen(true)}>+ New broadcast</button>}/>{data.broadcasts.length?<div className="marketing-card-grid">{data.broadcasts.map(b=><article className="marketing-card" key={b.id}><div className="marketing-card__top"><div><span className="micro">{dt(b.created_at)}</span><h3>{b.name}</h3></div><Status value={b.status}/></div><div className="marketing-metrics"><div><span>Audience</span><b>{Number(b.recipients||b.audience_snapshot_count).toLocaleString()}</b></div><div><span>Sent</span><b>{Number(b.sent_count).toLocaleString()}</b></div><div><span>Clicks</span><b>{Number(b.clickers).toLocaleString()}</b></div><div><span>Sales</span><b>{Number(b.conversions).toLocaleString()}</b></div></div><div className="marketing-card__revenue"><div><span>Attributed revenue</span><strong>{money(b.revenue_br)}</strong></div><small>{Number(b.blocked_count||0).toLocaleString()} blocked · {Number(b.failed_count||0).toLocaleString()} failed</small></div><div className="card-actions">{['draft','scheduled'].includes(b.status)&&<button className="btn btn--small" onClick={()=>setOpen(b)}>Edit</button>}{b.status==='draft'&&<button className="btn btn--green btn--small" onClick={async()=>{await api.scheduleBroadcast(b.id,null);await reload()}}>Send now</button>}{['scheduled','sending'].includes(b.status)&&<button className="btn btn--danger-quiet btn--small" onClick={async()=>{await api.cancelBroadcast(b.id);await reload()}}>Cancel</button>}</div></article>)}</div>:<Empty title="No broadcasts yet" text="Create a targeted Telegram campaign from here."/>}{open&&<BroadcastEditor products={data.products} existing={typeof open==='object'?open:undefined} onClose={()=>setOpen(false)} onDone={reload}/>}</div>}

function AutomationEditor({products,existing,onClose,onDone}:{products:MarketingProduct[];existing?:Automation;onClose:()=>void;onDone:()=>Promise<void>}){
 const[name,setName]=useState(existing?.name||'Recovery · product viewed')
 const[product,setProduct]=useState(existing?.product_id||products[0]?.id||'')
 const[trigger,setTrigger]=useState(existing?.trigger_event||'PRODUCT_VIEWED')
 const[firstWait,setFirstWait]=useState('4');const[secondWait,setSecondWait]=useState('20');const[price,setPrice]=useState('299');const[expiry,setExpiry]=useState('24')
 const[am1,setAm1]=useState('');const[en1,setEn1]=useState('');const[am2,setAm2]=useState('');const[en2,setEn2]=useState('')
 const[busy,setBusy]=useState(false);const[loadingExisting,setLoadingExisting]=useState(Boolean(existing));const[error,setError]=useState('')
 useEffect(()=>{if(!existing)return;let live=true;(async()=>{try{const detail=await api.automation(existing.id);if(!live)return;const byKey=new Map(detail.steps.map(s=>[s.step_key,s]));const hours=(key:string)=>String(Math.max(.01,Number(asObj(byKey.get(key)?.config).seconds||3600)/3600));setFirstWait(hours('wait_proof'));setSecondWait(hours('wait_recovery'));const offer=asObj(byKey.get('unlock_offer')?.config);if(offer.price_br)setPrice(String(offer.price_br));if(offer.expires_after_seconds)setExpiry(String(Number(offer.expires_after_seconds)/3600));const proof=asObj(byKey.get('proof_message')?.config);setAm1(asString(proof.am));setEn1(asString(proof.en));const msg=asObj(byKey.get('offer_message')?.config);setAm2(asString(msg.am));setEn2(asString(msg.en))}catch(e){if(live)setError(e instanceof Error?e.message:'Could not load automation')}finally{if(live)setLoadingExisting(false)}})();return()=>{live=false}},[existing])
 const submit=async()=>{setBusy(true);setError('');try{const h=(v:string)=>Math.max(60,Math.round(Number(v||1)*3600));const steps=[
  {step_key:'wait_proof',step_type:'wait',config:{seconds:h(firstWait)}},
  {step_key:'proof_message',step_type:'send_message',config:{am:am1,en:en1,button_text_am:'📘 ይመልከቱ',button_text_en:'📘 Take a look'}},
  {step_key:'wait_recovery',step_type:'wait',config:{seconds:h(secondWait)}},
  {step_key:'still_not_bought',step_type:'condition',config:{condition:'not_purchased'}},
  {step_key:'no_pending_payment',step_type:'condition',config:{condition:'no_pending_payment'}},
  {step_key:'unlock_offer',step_type:'create_offer',config:{price_br:price,expires_after_seconds:h(expiry)}},
  {step_key:'offer_message',step_type:'send_message',config:{am:am2,en:en2,button_text_am:`💚 ${price} ብር`,button_text_en:`💚 Get it for ${price} Br`}},
  {step_key:'done',step_type:'stop',config:{reason:'recovery_offer_sent'}},
 ];const payload={name,product_id:product,trigger_event:trigger,is_enabled:existing?.is_enabled||false,audience_definition:{kind:'non_buyers',product_id:product},trigger_config:{stop_on_purchase:true,stop_on_pending_payment:true},steps,...(existing?{expected_revision:existing.revision}:{})};if(existing)await api.updateAutomation(existing.id,payload);else await api.createAutomation(payload);await onDone();onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save automation')}finally{setBusy(false)}}
 return <Modal title={existing?'Edit recovery automation':'New recovery automation'} onClose={onClose}><div className="marketing-editor"><div className="marketing-form-grid"><label>Name<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label>Product<ProductSelect products={products} value={product} onChange={setProduct} required/></label><label>Trigger<select className="field" value={trigger} onChange={e=>setTrigger(e.target.value)}><option>PRODUCT_VIEWED</option><option>PREVIEW_VIEWED</option><option>BUY_CLICKED</option><option>BOT_STARTED</option><option>ONBOARDING_COMPLETED</option><option>PAYMENT_REJECTED</option></select></label><label>First wait · hours<input className="field" type="number" min="0.1" step="0.1" value={firstWait} onChange={e=>setFirstWait(e.target.value)}/></label></div><div className="automation-flow"><span>TRIGGER</span><i>↓</i><b>Wait {firstWait}h</b><i>↓</i><b>Send proof / value</b><i>↓</i><b>Wait {secondWait}h</b><i>↓</i><b>Purchased? → stop</b><i>↓</i><b>Payment pending? → stop</b><i>↓</i><strong>Unlock {price} Br</strong></div><div className="language-copy-grid"><label>Proof/value · AM<textarea className="field textarea" value={am1} onChange={e=>setAm1(e.target.value)}/></label><label>Proof/value · EN<textarea className="field textarea" value={en1} onChange={e=>setEn1(e.target.value)}/></label></div><div className="marketing-form-grid"><label>Second wait · hours<input className="field" type="number" min="1" value={secondWait} onChange={e=>setSecondWait(e.target.value)}/></label><label>Recovery price<input className="field" type="number" min="1" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Offer expires · hours<input className="field" type="number" min="1" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label></div><div className="language-copy-grid"><label>Offer message · AM<textarea className="field textarea" value={am2} onChange={e=>setAm2(e.target.value)}/></label><label>Offer message · EN<textarea className="field textarea" value={en2} onChange={e=>setEn2(e.target.value)}/></label></div><div className="locked-rule"><span>SAFETY RULES</span><b>Paid or payment-pending customers stop automatically.</b><p>Discounted orders remain non-commissionable. Eligibility is checked again when the delayed step actually runs.</p></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="btn btn--green" onClick={()=>void submit()} disabled={busy||loadingExisting||!product}>{loadingExisting?'Loading…':busy?'Saving…':existing?'Save automation':'Create disabled automation'}</button></div></div></Modal>
}

function Automations({data,reload}:{data:MarketingDashboard;reload:()=>Promise<void>}){const[open,setOpen]=useState<Automation|boolean>(false);return <div className="marketing-pane"><SectionHead title="Retargeting Automations" subtitle="Event-driven flows live in PostgreSQL. Change waits, messages and recovery timing here — not in Python." action={<button className="btn btn--green" onClick={()=>setOpen(true)}>+ New automation</button>}/>{data.automations.length?<div className="automation-list">{data.automations.map((a:Automation)=><article className="automation-row" key={a.id}><div className={`automation-toggle ${a.is_enabled?'on':''}`}><i/></div><div className="automation-main"><div><span className="micro">{a.trigger_event.replaceAll('_',' ')}</span><h3>{a.name}</h3><p>{a.product_title||'All products'} · {a.step_count} steps · {a.active_runs} active runs</p></div><div className="automation-stats"><span>{a.runs_30d} runs · 30d</span><b>v{a.version}</b></div></div><div className="card-actions"><button className="btn btn--small" onClick={()=>setOpen(a)}>Edit</button><button className={`btn btn--small ${a.is_enabled?'btn--danger-quiet':'btn--green'}`} onClick={async()=>{await api.setAutomationEnabled(a.id,!a.is_enabled);await reload()}}>{a.is_enabled?'Disable':'Enable'}</button></div></article>)}</div>:<Empty title="No automations" text="Build the first recovery path, leave it disabled, review it, then turn it on."/>}{open&&<AutomationEditor products={data.products} existing={typeof open==='object'?open:undefined} onClose={()=>setOpen(false)} onDone={reload}/>}</div>}

function DiscountEditor({products,existing,onClose,onDone}:{products:MarketingProduct[];existing?:DiscountRule;onClose:()=>void;onDone:()=>Promise<void>}){const[product,setProduct]=useState(existing?.product_id||products.find(p=>p.discounts_enabled)?.id||products[0]?.id||'');const[name,setName]=useState(existing?.name||'Recovery offer');const[price,setPrice]=useState(String(existing?.target_price_br||299));const[expiry,setExpiry]=useState(String(existing?.expires_after_seconds?existing.expires_after_seconds/3600:24));const[score,setScore]=useState(String(existing?.minimum_intent_score||0));const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);setError('');try{const payload={product_id:product,name,target_price_br:price,expires_after_seconds:Number(expiry)*3600,minimum_intent_score:Number(score),require_no_pending_payment:true,is_active:existing?.is_active??true,...(existing?{expected_revision:existing.revision}:{})};if(existing)await api.updateDiscountRule(existing.id,payload);else await api.createDiscountRule(payload);await onDone();onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save rule')}finally{setBusy(false)}};return <Modal title={existing?'Edit discount rule':'New discount rule'} onClose={onClose}><div className="marketing-editor"><div className="marketing-form-grid"><label>Product<ProductSelect products={products} value={product} onChange={setProduct} required disabled={Boolean(existing)}/></label><label>Rule name<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label>Offer price<input className="field" type="number" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Expires after · hours<input className="field" type="number" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label>Min intent score<input className="field" type="number" min="0" value={score} onChange={e=>setScore(e.target.value)}/></label></div><div className="locked-rule"><span>LOCKED</span><b>Discount sales pay 0 Br referral commission.</b><p>Pending-payment and paid customers are excluded from recovery offer creation.</p></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="btn btn--green" disabled={busy} onClick={()=>void submit()}>{busy?'Saving…':existing?'Save rule':'Create rule'}</button></div></div></Modal>}

function Discounts({data,reload}:{data:MarketingDashboard;reload:()=>Promise<void>}){const[open,setOpen]=useState<DiscountRule|boolean>(false);return <div className="marketing-pane"><SectionHead title="Recovery Offers" subtitle="Pricing rules and live customer offers. Recovery is earned by eligibility — never shown to everyone immediately." action={<button className="btn btn--green" onClick={()=>setOpen(true)}>+ New rule</button>}/><div className="discount-layout"><div>{data.discount_rules.length?data.discount_rules.map(r=><article className="discount-rule" key={r.id}><div><span className="micro">{r.product_title}</span><h3>{r.name}</h3><p><s>{money(r.regular_price_br)}</s> → <strong>{money(r.target_price_br)}</strong> · {r.expires_after_seconds?`${Math.round(r.expires_after_seconds/3600)}h expiry`:'No expiry'}</p></div><div><span>{r.live_offers} live</span><span>{r.redeemed_offers} redeemed</span><button className="btn btn--small" onClick={()=>setOpen(r)}>Edit</button><button className={`btn btn--small ${r.is_active?'btn--danger-quiet':'btn--green'}`} onClick={async()=>{await api.setDiscountRuleEnabled(r.id,!r.is_active);await reload()}}>{r.is_active?'Disable':'Enable'}</button></div></article>):<Empty title="No recovery rules"/>}</div><aside className="live-offers"><h3>Latest customer offers</h3>{data.offers.slice(0,12).map(o=><div key={o.id}><span>{o.first_name} · {o.product_title}</span><b>{money(o.offer_price_br)}</b><Status value={o.status}/></div>)}{!data.offers.length&&<p>No offers yet.</p>}</aside></div>{open&&<DiscountEditor products={data.products} existing={typeof open==='object'?open:undefined} onClose={()=>setOpen(false)} onDone={reload}/>}</div>}

function PayoutModal({partner,onClose,onDone}:{partner:ReferralPartner;onClose:()=>void;onDone:()=>Promise<void>}){const[method,setMethod]=useState(partner.payout_method||'cbe');const[destination,setDestination]=useState(partner.payout_destination||'');const[note,setNote]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async()=>{setBusy(true);try{await api.createPayout({referrer_user_id:partner.user_id,payout_method:method,payout_destination:destination,note});await onDone();onClose()}catch(e){setError(e instanceof Error?e.message:'Could not create payout')}finally{setBusy(false)}};return <Modal title={`Pay ${partner.first_name}`} onClose={onClose}><div className="marketing-editor"><div className="payout-total"><span>Available commission</span><strong>{money(partner.available_br)}</strong></div><label>Method<select className="field" value={method} onChange={e=>setMethod(e.target.value)}><option value="cbe">CBE</option><option value="telebirr">Telebirr</option><option value="other">Other</option></select></label><label>Destination<input className="field" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Account / phone"/></label><label>Internal note<textarea className="field textarea" value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="btn btn--green" disabled={busy||!destination} onClick={()=>void submit()}>{busy?'Creating…':'Create payout'}</button></div></div></Modal>}

function Referrals({data,reload}:{data:MarketingDashboard;reload:()=>Promise<void>}){const[pay,setPay]=useState<ReferralPartner|null>(null);const s=data.referrals.summary;return <div className="marketing-pane"><SectionHead title="Referrals & Payouts" subtitle="Full-price referrals only. Discount orders never enter the commission ledger."/><div className="mini-kpis"><div><span>Partners</span><b>{Number(s.partners||0)}</b></div><div><span>Referred users</span><b>{Number(s.referred_users||0)}</b></div><div><span>Available</span><b>{money(s.available_br as number|string)}</b></div><div><span>Paid</span><b>{money(s.paid_br as number|string)}</b></div></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Partner</th><th>Joins</th><th>Full-price sales</th><th>Available</th><th>Total paid</th><th/></tr></thead><tbody>{data.referrals.partners.map(p=><tr key={p.id}><td><b>{p.first_name}</b><span>{p.username?`@${p.username}`:p.telegram_id} · ref_{p.code}</span></td><td>{p.joins}</td><td>{p.paid_referrals}</td><td>{money(p.available_br)}</td><td>{money(p.paid_br)}</td><td>{Number(p.available_br)>0&&<button className="btn btn--green btn--small" onClick={()=>setPay(p)}>Pay</button>}</td></tr>)}</tbody></table></div></div><SectionHead title="Payout history"/><div className="payout-list">{data.referrals.payouts.map(p=><article key={p.id}><div><b>{p.first_name}</b><span>{p.payout_method.toUpperCase()} · {p.commission_count} commissions · {dt(p.created_at)}</span></div><strong>{money(p.amount_br)}</strong><Status value={p.status}/>{p.status==='pending'&&<button className="btn btn--green btn--small" onClick={async()=>{await api.markPayoutPaid(p.id);await reload()}}>Mark paid</button>}</article>)}</div>{pay&&<PayoutModal partner={pay} onClose={()=>setPay(null)} onDone={reload}/>}</div>}

function LinkEditor({products,onClose,onDone}:{products:MarketingProduct[];onClose:()=>void;onDone:()=>Promise<void>}){const[product,setProduct]=useState(products[0]?.id||'');const[label,setLabel]=useState('');const[source,setSource]=useState('Facebook');const[campaign,setCampaign]=useState('');const[creative,setCreative]=useState('');const[angle,setAngle]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async()=>{setBusy(true);try{await api.createTrackingLink({product_id:product||null,label,source,platform:'Facebook',campaign,creative,angle,language_hint:'am'});await onDone();onClose()}catch(e){setError(e instanceof Error?e.message:'Could not create link')}finally{setBusy(false)}};return <Modal title="New ad link" onClose={onClose}><div className="marketing-editor"><div className="marketing-form-grid"><label>Product<ProductSelect products={products} value={product} onChange={setProduct}/></label><label>Internal label<input className="field" value={label} onChange={e=>setLabel(e.target.value)} placeholder="A03 beginner confusion"/></label><label>Source<input className="field" value={source} onChange={e=>setSource(e.target.value)}/></label><label>Campaign<input className="field" value={campaign} onChange={e=>setCampaign(e.target.value)}/></label><label>Creative<input className="field" value={creative} onChange={e=>setCreative(e.target.value)}/></label><label>Angle<input className="field" value={angle} onChange={e=>setAngle(e.target.value)}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><button className="btn btn--green" disabled={busy} onClick={()=>void submit()}>{busy?'Creating…':'Create hidden start link'}</button></div></div></Modal>}

function Links({data,reload}:{data:MarketingDashboard;reload:()=>Promise<void>}){const[open,setOpen]=useState(false);const copy=async(v:string)=>navigator.clipboard.writeText(v);return <div className="marketing-pane"><SectionHead title="Ad Links" subtitle="Short database-backed Telegram start tokens. Product, campaign and creative stay server-side." action={<button className="btn btn--green" onClick={()=>setOpen(true)}>+ New ad link</button>}/>{data.links.length?<div className="link-list">{data.links.map(l=>{const botUrl=(l as typeof l&{bot_url?:string}).bot_url||`?start=src_${l.token}`;return <article key={l.id}><div className="link-status"><i className={l.is_active?'on':''}/></div><div className="link-main"><span className="micro">{l.source} · {l.creative||'no creative'}</span><h3>{l.label||l.campaign||l.token}</h3><code>{botUrl}</code><p>{l.product_title||'No product'} · {l.starts} starts · {l.purchases} purchases · {money(l.revenue_br)}</p></div><div className="card-actions"><button className="btn btn--small" onClick={()=>void copy(botUrl)}>Copy</button><button className={`btn btn--small ${l.is_active?'btn--danger-quiet':'btn--green'}`} onClick={async()=>{await api.setTrackingLinkEnabled(l.id,!l.is_active);await reload()}}>{l.is_active?'Disable':'Enable'}</button></div></article>})}</div>:<Empty title="No ad links"/>}{open&&<LinkEditor products={data.products} onClose={()=>setOpen(false)} onDone={reload}/>}</div>}

export function MarketingView({data,reload}:{data:MarketingDashboard;reload:()=>Promise<void>}){
 const[tab,setTab]=useState<Tab>('broadcasts');const o=data.overview;const subtitle=useMemo(()=>`${o.active_automations} automations live · ${o.live_offers} recovery offers active`,[o])
 return <div className="page-stack marketing-page"><SectionHead title="Marketing" subtitle={subtitle}/><div className="marketing-kpis"><Kpi eyebrow="Broadcast revenue · 30d" value={money(o.broadcast_revenue_30d_br)} note={`${o.broadcasts_30d} campaigns`} icon="send"/><Kpi eyebrow="Active automations" value={o.active_automations} note="event-driven" icon="pulse"/><Kpi eyebrow="Commission owed" value={money(o.commission_owed_br)} note={`${o.referral_partners} partners`} icon="wallet"/><Kpi eyebrow="Ad links" value={o.active_ad_links} note="active hidden starts" icon="arrow"/></div><div className="marketing-tabs">{tabs.map(t=><button className={tab===t.id?'active':''} onClick={()=>setTab(t.id)} key={t.id}>{t.label}</button>)}</div>{tab==='broadcasts'&&<Broadcasts data={data} reload={reload}/>} {tab==='automations'&&<Automations data={data} reload={reload}/>} {tab==='discounts'&&<Discounts data={data} reload={reload}/>} {tab==='referrals'&&<Referrals data={data} reload={reload}/>} {tab==='links'&&<Links data={data} reload={reload}/>}</div>
}
