import { useState } from 'react'
import type { Payment } from '../api/types'
import { api } from '../api/client'
import { Icon } from '../components/Icon'
import { Empty, Modal, SectionHead, Status, ago, label, money } from '../components/UI'

const reasons=[['wrong_amount','💰 Wrong amount'],['wrong_receiver','👤 Wrong receiver'],['unclear_screenshot','📸 Screenshot unclear'],['old_transaction','🕐 Old transaction'],['duplicate_receipt','♻️ Duplicate receipt'],['transaction_not_found','🔎 Transaction not found'],['other','✏️ Other']] as const

function reviewAge(payment:Payment){
 const minutes=Math.max(0,Math.floor(Number(payment.review_wait_seconds||0)/60))
 return {minutes,label:minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}m`:`${minutes}m`,level:minutes>=30?'urgent':minutes>=15?'waiting':'new'}
}

export function PaymentsView({items,reload}:{items:Payment[];reload:()=>Promise<void>}){
 const [filter,setFilter]=useState('review'); const [reject,setReject]=useState<Payment|null>(null); const [reason,setReason]=useState('unclear_screenshot'); const [custom,setCustom]=useState(''); const [busy,setBusy]=useState<string>('')
 const shown=items.filter(p=>filter==='all'||filter==='review'&&['pending_review','flagged'].includes(p.status)||p.status===filter)
 const reviewQueue=items.filter(p=>['pending_review','flagged'].includes(p.status)); const urgent=reviewQueue.filter(p=>reviewAge(p).minutes>=30).length; const waiting=reviewQueue.filter(p=>reviewAge(p).minutes>=15).length
 const act=async(kind:'approve'|'flag',p:Payment)=>{setBusy(p.public_id+kind);try{kind==='approve'?await api.approvePayment(p.public_id,p.latest_proof_id):await api.flagPayment(p.public_id,p.latest_proof_id);await reload()}finally{setBusy('')}}
 const submitReject=async()=>{if(!reject)return;setBusy(reject.public_id+'reject');try{await api.rejectPayment(reject.public_id,reject.latest_proof_id,reason,reason==='other'?custom:undefined);setReject(null);setCustom('');await reload()}finally{setBusy('')}}
 return <div className="page-stack"><SectionHead title="Payments" subtitle="Oldest receipts appear first. Approve once; the backend handles the rest." action={<div className="segmented">{['review','all','approved','rejected'].map(v=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{label(v)}</button>)}</div>}/>
  {reviewQueue.length>0&&<div className="review-queue-summary"><div><span>In review</span><b>{reviewQueue.length}</b></div><div className={waiting?'waiting':''}><span>Waiting 15m+</span><b>{waiting}</b></div><div className={urgent?'urgent':''}><span>Needs attention · 30m+</span><b>{urgent}</b></div></div>}
  {shown.length===0?<Empty title="Payment queue clear" text="Nothing needs review right now."/>:<div className="payment-grid">{shown.map(p=>{const age=reviewAge(p);const reviewing=['pending_review','flagged'].includes(p.status);return <article className={`payment-card ${reviewing?`payment-card--${age.level}`:''}`} key={p.id}><div className="payment-card__receipt">{p.latest_proof_id?<img src={api.proofImage(p.latest_proof_id)} alt={`Receipt ${p.public_id}`}/>:<div className="receipt-empty">No screenshot yet</div>}<span>{p.payment_method.toUpperCase()}</span>{reviewing&&<b className={`review-age review-age--${age.level}`}>{age.level==='urgent'?'Needs attention':age.level==='waiting'?'Waiting':'New'} · {age.label}</b>}</div><div className="payment-card__body"><div className="payment-card__top"><div><span className="micro">{p.public_id}</span><h3>{p.first_name} · {p.product_title}</h3></div><Status value={p.status}/></div><div className="payment-amount"><strong>{money(p.expected_amount_br)}</strong><span>{p.pricing_type==='regular'?'FULL PRICE':'DISCOUNT · NO COMMISSION'}</span></div><div className="payment-meta"><div><span>Order</span><b>{p.order_public_id}</b></div><div><span>Source</span><b>{p.creative||p.campaign||p.platform||'Direct'}</b></div><div><span>Referral</span><b>{p.referrer_username?`@${p.referrer_username}`:'None'}</b></div><div><span>Waiting</span><b>{ago(p.proof_created_at||p.updated_at)}</b></div></div>{reviewing&&<div className="payment-actions"><button className="btn btn--approve" disabled={!!busy} onClick={()=>void act('approve',p)}><Icon name="check"/> Approve</button><button className="btn btn--reject" disabled={!!busy} onClick={()=>setReject(p)}><Icon name="x"/> Reject</button>{p.status!=='flagged'&&<button className="btn btn--quiet" disabled={!!busy} onClick={()=>void act('flag',p)}><Icon name="flag"/> Flag</button>}</div>}</div></article>})}</div>}
  {reject&&<Modal title={`Reject ${reject.public_id}`} onClose={()=>setReject(null)}><div className="reject-reasons">{reasons.map(([value,text])=><button className={reason===value?'active':''} onClick={()=>setReason(value)} key={value}>{text}</button>)}</div>{reason==='other'&&<textarea className="field textarea" placeholder="Exact reason the customer should see…" value={custom} onChange={e=>setCustom(e.target.value)}/>}<div className="modal-actions"><button className="btn btn--quiet" onClick={()=>setReject(null)}>Cancel</button><button className="btn btn--reject" disabled={!!busy||(reason==='other'&&!custom.trim())} onClick={()=>void submitReject()}><Icon name="x"/> Reject payment</button></div></Modal>}
 </div>
}
