import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { api } from '../api/client'
import type { Product, ProductDetail, ProductRelationship } from '../api/types'
import { Icon } from '../components/Icon'
import { Empty, Loading, Modal, SectionHead, Status, money } from '../components/UI'

type Tab='basics'|'am'|'en'|'media'|'delivery'|'salesman'|'upsells'
const tabs:Array<{id:Tab;label:string}>=[
  {id:'basics',label:'Basics & Pricing'},{id:'am',label:'Store · AM'},{id:'en',label:'Store · EN'},
  {id:'media',label:'Media'},{id:'delivery',label:'Delivery'},{id:'salesman',label:'Bot Salesman'},{id:'upsells',label:'Upsells'},
]

const lines=(v:string)=>v.split('\n').map(x=>x.trim()).filter(Boolean)
const faqParse=(v:string)=>v.split('\n').map(x=>x.trim()).filter(Boolean).map(row=>{const [q,...rest]=row.split('||');return{question:q?.trim()||'',answer:rest.join('||').trim()}}).filter(x=>x.question&&x.answer)
const faqText=(v:Array<{question:string;answer:string}>|undefined)=>((v||[]).map(x=>`${x.question} || ${x.answer}`).join('\n'))

function CreateProduct({onClose,onCreated}:{onClose:()=>void;onCreated:(p:ProductDetail)=>void}){
  const[busy,setBusy]=useState(false);const[err,setErr]=useState('')
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setErr('');const f=new FormData(e.currentTarget);try{const d=await api.createProduct({slug:f.get('slug'),title:f.get('title'),product_type:f.get('product_type'),category:f.get('category')||null,default_language:f.get('default_language'),regular_price_br:Number(f.get('regular_price_br')),recovery_price_br:f.get('recovery_price_br')?Number(f.get('recovery_price_br')):null,discounts_enabled:Boolean(f.get('discounts_enabled')),referral_enabled:true,referral_commission_percent:10,featured:false,sort_order:0});onCreated(d)}catch(x){setErr(x instanceof Error?x.message:'Could not create product')}finally{setBusy(false)}}
  return <Modal title="Create product" onClose={onClose}><form className="product-create-form" onSubmit={e=>void submit(e)}><p className="form-lead">Create the commercial shell first. Everything else is edited on the product workspace.</p><div className="form-grid"><label>Product title<input className="field" name="title" placeholder="AI ከዜሮ" required/></label><label>Slug<input className="field" name="slug" placeholder="ai-kezero" required/></label><label>Type<select className="field" name="product_type" defaultValue="digital_file"><option value="digital_file">Digital file</option><option value="digital_bundle">Digital bundle</option><option value="course">Course</option><option value="service">Service</option><option value="other">Other</option></select></label><label>Default language<select className="field" name="default_language" defaultValue="am"><option value="am">Amharic</option><option value="en">English</option></select></label><label>Regular price (Br)<input className="field" name="regular_price_br" type="number" min="1" step="0.01" required/></label><label>Recovery price (optional)<input className="field" name="recovery_price_br" type="number" min="1" step="0.01"/></label><label className="span-2">Category<input className="field" name="category" placeholder="AI / Practical Guide"/></label><label className="check-row span-2"><input type="checkbox" name="discounts_enabled"/> Enable recovery-price engine for this product</label></div>{err&&<p className="form-error">{err}</p>}<div className="modal-actions"><button type="button" className="btn btn--quiet" onClick={onClose}>Cancel</button><button className="btn btn--green" disabled={busy}>{busy?'Creating…':'Create product'}</button></div></form></Modal>
}

function TranslationEditor({detail,language,onSaved}:{detail:ProductDetail;language:'am'|'en';onSaved:()=>Promise<void>}){
  const t=detail.translations[language]
  const[title,setTitle]=useState(t?.title||'');const[subtitle,setSubtitle]=useState(t?.subtitle||'');const[short,setShort]=useState(t?.short_description||'');const[desc,setDesc]=useState(t?.description||'');const[benefits,setBenefits]=useState((t?.benefits||[]).join('\n'));const[faq,setFaq]=useState(faqText(t?.faq));const[busy,setBusy]=useState(false);const[err,setErr]=useState('')
  useEffect(()=>{const x=detail.translations[language];setTitle(x?.title||'');setSubtitle(x?.subtitle||'');setShort(x?.short_description||'');setDesc(x?.description||'');setBenefits((x?.benefits||[]).join('\n'));setFaq(faqText(x?.faq))},[detail,language])
  const save=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErr('');try{await api.saveProductTranslation(detail.product.id,language,{expected_revision:t?.revision||null,title,subtitle:subtitle||null,short_description:short||null,description:desc||null,benefits:lines(benefits),faq:faqParse(faq)});await onSaved()}catch(x){setErr(x instanceof Error?x.message:'Save failed')}finally{setBusy(false)}}
  return <form className="editor-form" onSubmit={e=>void save(e)}><div className="editor-section-head"><div><span>{language==='am'?'AMHARIC STOREFRONT':'ENGLISH STOREFRONT'}</span><h3>What customers see</h3></div><button className="btn btn--green" disabled={busy}>{busy?'Saving…':'Save language'}</button></div>{err&&<p className="form-error">{err}</p>}<div className="form-grid"><label className="span-2">Title<input className="field" value={title} onChange={e=>setTitle(e.target.value)} required/></label><label className="span-2">Subtitle<input className="field" value={subtitle} onChange={e=>setSubtitle(e.target.value)}/></label><label className="span-2">Short description<textarea className="field textarea textarea--sm" value={short} onChange={e=>setShort(e.target.value)}/></label><label className="span-2">Full description<textarea className="field textarea textarea--lg" value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Benefits <small>One benefit per line</small><textarea className="field textarea" value={benefits} onChange={e=>setBenefits(e.target.value)} placeholder={'Practical examples\n27+ ready-to-use prompts'}/></label><label>FAQ <small>One row: Question || Answer</small><textarea className="field textarea" value={faq} onChange={e=>setFaq(e.target.value)} placeholder={'Who is this for? || Beginners who want practical AI use.\nDo I need perfect English? || No.'}/></label></div></form>
}

function ProductEditor({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged:()=>Promise<void>}){
  const[detail,setDetail]=useState<ProductDetail|null>(null);const[tab,setTab]=useState<Tab>('basics');const[busy,setBusy]=useState(false);const[err,setErr]=useState('')
  const load=async()=>{setErr('');try{setDetail(await api.product(id))}catch(x){setErr(x instanceof Error?x.message:'Could not load product')}}
  useEffect(()=>{void load()},[id])
  const p=detail?.product
  const[slug,setSlug]=useState('');const[type,setType]=useState('digital_file');const[category,setCategory]=useState('');const[defaultLanguage,setDefaultLanguage]=useState<'am'|'en'>('am');const[regular,setRegular]=useState('');const[recovery,setRecovery]=useState('');const[discounts,setDiscounts]=useState(false);const[referral,setReferral]=useState(true);const[commission,setCommission]=useState('10');const[featured,setFeatured]=useState(false);const[sortOrder,setSortOrder]=useState('0')
  useEffect(()=>{if(!p)return;setSlug(p.slug);setType(p.product_type);setCategory(p.category||'');setDefaultLanguage(p.default_language||'am');setRegular(String(p.regular_price_br));setRecovery(p.recovery_price_br?String(p.recovery_price_br):'');setDiscounts(p.discounts_enabled);setReferral(p.referral_enabled);setCommission(String(p.referral_commission_percent));setFeatured(p.featured);setSortOrder(String(p.sort_order))},[p])
  const saveCore=async(e:FormEvent)=>{e.preventDefault();if(!p)return;setBusy(true);setErr('');try{setDetail(await api.updateProduct(p.id,{expected_revision:p.revision,slug,product_type:type,category:category||null,default_language:defaultLanguage,regular_price_br:Number(regular),recovery_price_br:recovery?Number(recovery):null,discounts_enabled:discounts,referral_enabled:referral,referral_commission_percent:Number(commission),featured,sort_order:Number(sortOrder)}));await onChanged()}catch(x){setErr(x instanceof Error?x.message:'Save failed')}finally{setBusy(false)}}
  const statusAction=async(action:'publish'|'hide'|'draft'|'archive')=>{if(!p)return;setBusy(true);setErr('');try{const d=action==='publish'?await api.publishProduct(p.id):action==='hide'?await api.hideProduct(p.id):action==='draft'?await api.draftProduct(p.id):await api.archiveProduct(p.id);setDetail(d);await onChanged()}catch(x){setErr(x instanceof Error?x.message:'Status change failed')}finally{setBusy(false)}}

  const[mediaType,setMediaType]=useState('gallery');const[mediaUrl,setMediaUrl]=useState('');const[mediaLang,setMediaLang]=useState('');const[mediaAlt,setMediaAlt]=useState('');const[uploading,setUploading]=useState(false)
  const addMediaUrl=async()=>{if(!p||!mediaUrl.trim())return;setUploading(true);setErr('');try{await api.addProductMedia(p.id,{media_type:mediaType,storage_type:'url',value:mediaUrl.trim(),language:mediaLang||null,alt_text:mediaAlt||null,sort_order:0});setMediaUrl('');await load()}catch(x){setErr(x instanceof Error?x.message:'Media save failed')}finally{setUploading(false)}}
  const uploadMedia=async(file:File|null)=>{if(!p||!file)return;setUploading(true);setErr('');const f=new FormData();f.append('file',file);f.append('media_type',mediaType);if(mediaLang)f.append('language',mediaLang);if(mediaAlt)f.append('alt_text',mediaAlt);try{await api.uploadProductMedia(p.id,f);await load()}catch(x){setErr(x instanceof Error?x.message:'Upload failed')}finally{setUploading(false)}}
  const removeMedia=async(mid:string)=>{if(!p)return;setUploading(true);try{await api.removeProductMedia(p.id,mid);await load()}catch(x){setErr(x instanceof Error?x.message:'Remove failed')}finally{setUploading(false)}}

  const[fileVersion,setFileVersion]=useState('v1.0');const[fileNotes,setFileNotes]=useState('');const[fileId,setFileId]=useState('');const[fileName,setFileName]=useState('');const[fileBusy,setFileBusy]=useState(false)
  const uploadDelivery=async(file:File|null)=>{if(!p||!file||!fileVersion.trim())return;setFileBusy(true);setErr('');const f=new FormData();f.append('file',file);f.append('version',fileVersion.trim());f.append('release_notes',fileNotes);f.append('activate','true');try{await api.uploadProductFile(p.id,f);await load()}catch(x){setErr(x instanceof Error?x.message:'Delivery upload failed')}finally{setFileBusy(false)}}
  const addExistingFile=async()=>{if(!p||!fileId.trim()||!fileName.trim()||!fileVersion.trim())return;setFileBusy(true);try{await api.addProductFile(p.id,{version:fileVersion.trim(),telegram_file_id:fileId.trim(),file_name:fileName.trim(),release_notes:fileNotes||null,activate:true});setFileId('');setFileName('');await load()}catch(x){setErr(x instanceof Error?x.message:'File save failed')}finally{setFileBusy(false)}}

  const[salesLang,setSalesLang]=useState<'am'|'en'>('am');const[audience,setAudience]=useState('default');const[hook,setHook]=useState('');const[preview,setPreview]=useState('');const[objection,setObjection]=useState('');const[salesBusy,setSalesBusy]=useState(false)
  const contentText=(key:string)=>{const b=detail?.content_blocks.find(x=>x.language===salesLang&&x.block_key===key&&x.audience_key===audience);const c=b?.content||{};return String(c.html||c.text||'')}
  useEffect(()=>{setHook(contentText('sales_hook'));setPreview(contentText('sales_preview'));setObjection(contentText('sales_objection'))},[detail,salesLang,audience])
  const saveSales=async()=>{if(!p)return;setSalesBusy(true);setErr('');try{await Promise.all([api.saveProductContent(p.id,salesLang,'sales_hook',audience,{html:hook}),api.saveProductContent(p.id,salesLang,'sales_preview',audience,{html:preview}),api.saveProductContent(p.id,salesLang,'sales_objection',audience,{html:objection})]);await load()}catch(x){setErr(x instanceof Error?x.message:'Sales copy save failed')}finally{setSalesBusy(false)}}

  const[rels,setRels]=useState<ProductRelationship[]>([]);const[target,setTarget]=useState('');const[relType,setRelType]=useState<'upsell'|'cross_sell'|'next'>('upsell');const[relBusy,setRelBusy]=useState(false)
  useEffect(()=>{setRels(detail?.relationships||[])},[detail])
  const addRel=()=>{if(!detail||!target||rels.some(r=>r.target_product_id===target&&r.relationship_type===relType))return;const c=detail.catalog_choices.find(x=>x.id===target);if(!c)return;setRels([...rels,{id:`local-${target}-${relType}`,target_product_id:target,relationship_type:relType,sort_order:rels.length,is_active:true,target_slug:c.slug,target_title:c.title}])}
  const saveRels=async()=>{if(!p)return;setRelBusy(true);try{const r=await api.saveProductRelationships(p.id,rels.map((x,i)=>({target_product_id:x.target_product_id,relationship_type:x.relationship_type,sort_order:i})));setRels(r.items);await load()}catch(x){setErr(x instanceof Error?x.message:'Upsells save failed')}finally{setRelBusy(false)}}

  if(!detail)return <div className="product-editor-wrap"><section className="product-editor"><div className="editor-loading">{err?<><p className="form-error">{err}</p><button className="btn" onClick={onClose}>Close</button></>:<Loading/>}</div></section></div>
  const readiness=detail.readiness
  return <div className="product-editor-wrap"><section className="product-editor"><header className="product-editor__top"><div className="product-editor__identity"><button className="icon-btn" onClick={onClose}><Icon name="close"/></button><div><span>{p?.slug}</span><h2>{detail.translations[p?.default_language||'am']?.title||p?.slug}</h2></div><Status value={p?.status||'draft'}/></div><div className="product-editor__actions">{p?.status==='active'?<button className="btn" disabled={busy} onClick={()=>void statusAction('hide')}>Hide from store</button>:<button className="btn btn--green" disabled={busy||!readiness.ready} onClick={()=>void statusAction('publish')}>Publish</button>}<button className="btn btn--quiet" disabled={busy} onClick={()=>void statusAction('archive')}>Archive</button></div></header><div className={`readiness-bar ${readiness.ready?'readiness-bar--ready':'readiness-bar--blocked'}`}><div><b>{readiness.ready?'Ready to publish':'Needs attention'}</b><span>{readiness.ready?(readiness.warnings[0]||'Core publishing checks passed.'):(readiness.blockers[0]||'Complete the missing product setup.')}</span></div><div className="readiness-checks">{Object.entries(readiness.checks).map(([k,v])=><span className={v?'ok':''} key={k}>{v?'✓':'•'} {k.replaceAll('_',' ')}</span>)}</div></div>{err&&<button className="editor-error" onClick={()=>setErr('')}>{err}<span>×</span></button>}<nav className="product-tabs">{tabs.map(x=><button className={tab===x.id?'active':''} onClick={()=>setTab(x.id)} key={x.id}>{x.label}</button>)}</nav><main className="product-editor__body">
  {tab==='basics'&&<form className="editor-form" onSubmit={e=>void saveCore(e)}><div className="editor-section-head"><div><span>PRODUCT CORE</span><h3>Catalog, pricing & referral</h3></div><button className="btn btn--green" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div><div className="form-grid"><label>Slug<input className="field" value={slug} onChange={e=>setSlug(e.target.value)}/></label><label>Product type<select className="field" value={type} onChange={e=>setType(e.target.value)}><option value="digital_file">Digital file</option><option value="digital_bundle">Digital bundle</option><option value="course">Course</option><option value="service">Service</option><option value="other">Other</option></select></label><label>Category<input className="field" value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Default language<select className="field" value={defaultLanguage} onChange={e=>setDefaultLanguage(e.target.value as 'am'|'en')}><option value="am">Amharic</option><option value="en">English</option></select></label><label>Regular price (Br)<input className="field" type="number" min="1" step="0.01" value={regular} onChange={e=>setRegular(e.target.value)}/></label><label>Recovery price (Br)<input className="field" type="number" min="1" step="0.01" value={recovery} onChange={e=>setRecovery(e.target.value)}/></label><label className="switch-row"><input type="checkbox" checked={discounts} onChange={e=>setDiscounts(e.target.checked)}/><span><b>Recovery discount</b><small>Discount sales remain 0% commission.</small></span></label><label className="switch-row"><input type="checkbox" checked={referral} onChange={e=>setReferral(e.target.checked)}/><span><b>Referral program</b><small>Available only on full-price purchases.</small></span></label><label>Referral %<input className="field" type="number" min="0" max="100" step="0.01" value={commission} onChange={e=>setCommission(e.target.value)} disabled={!referral}/></label><label>Store order<input className="field" type="number" value={sortOrder} onChange={e=>setSortOrder(e.target.value)}/></label><label className="check-row span-2"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/> Feature this product on Zemen Store</label></div><div className="locked-rule"><span>LOCKED BUSINESS RULE</span><b>Discounted orders can never create referral commission.</b><p>This is protected by the database, not just this switchboard.</p></div></form>}
  {tab==='am'&&<TranslationEditor detail={detail} language="am" onSaved={async()=>{await load();await onChanged()}}/>}
  {tab==='en'&&<TranslationEditor detail={detail} language="en" onSaved={async()=>{await load();await onChanged()}}/>}
  {tab==='media'&&<div className="editor-form"><div className="editor-section-head"><div><span>STORE MEDIA</span><h3>Cover, previews & gallery</h3></div></div><div className="media-uploader"><div className="form-grid"><label>Type<select className="field" value={mediaType} onChange={e=>setMediaType(e.target.value)}><option value="cover">Cover</option><option value="preview">Preview</option><option value="gallery">Gallery</option><option value="thumbnail">Thumbnail</option><option value="video">Video</option></select></label><label>Language<select className="field" value={mediaLang} onChange={e=>setMediaLang(e.target.value)}><option value="">All languages</option><option value="am">Amharic</option><option value="en">English</option></select></label><label className="span-2">Alt text<input className="field" value={mediaAlt} onChange={e=>setMediaAlt(e.target.value)} placeholder="Describe the image for accessibility"/></label><label className="span-2">Public URL<input className="field" value={mediaUrl} onChange={e=>setMediaUrl(e.target.value)} placeholder="https://..."/></label></div><div className="media-uploader__actions"><button className="btn" disabled={uploading||!mediaUrl.trim()} onClick={()=>void addMediaUrl()}>Add URL</button><label className={`btn btn--green ${uploading?'disabled':''}`}>{uploading?'Uploading…':'Upload to Telegram storage'}<input type="file" accept="image/*,video/*" hidden disabled={uploading} onChange={e=>void uploadMedia(e.target.files?.[0]||null)}/></label></div></div><div className="asset-grid">{detail.media.filter(x=>x.is_active).map(m=><article className="asset-card" key={m.id}><div className="asset-card__preview">{m.public_url&&m.mime_type?.startsWith('video/')?<video src={m.public_url} controls/>:m.public_url?<img src={m.public_url} alt={m.alt_text||''}/>:<div className="asset-placeholder"><Icon name="products"/></div>}<span>{m.media_type}</span></div><div className="asset-card__meta"><b>{m.file_name||m.alt_text||m.media_type}</b><small>{m.language?.toUpperCase()||'ALL'} · {m.storage_type.replaceAll('_',' ')}</small><button className="btn btn--danger-quiet" disabled={uploading} onClick={()=>void removeMedia(m.id)}>Remove</button></div></article>)}</div>{!detail.media.some(x=>x.is_active)&&<Empty title="No media yet" text="Add a cover first, then previews that help people judge the product."/>}</div>}
  {tab==='delivery'&&<div className="editor-form"><div className="editor-section-head"><div><span>DELIVERY</span><h3>Product file & versions</h3></div></div><div className="delivery-upload"><div className="form-grid"><label>Version<input className="field" value={fileVersion} onChange={e=>setFileVersion(e.target.value)} placeholder="v1.0"/></label><label>Release notes<input className="field" value={fileNotes} onChange={e=>setFileNotes(e.target.value)} placeholder="Initial release"/></label></div><label className={`drop-upload ${fileBusy?'disabled':''}`}><Icon name="delivery"/><b>{fileBusy?'Uploading to Telegram…':'Upload delivery file'}</b><span>The new version becomes the active file for future purchases.</span><input type="file" hidden disabled={fileBusy} onChange={e=>void uploadDelivery(e.target.files?.[0]||null)}/></label><details className="advanced-file"><summary>Already have a Telegram file_id?</summary><div className="form-grid"><label>Telegram file_id<input className="field" value={fileId} onChange={e=>setFileId(e.target.value)}/></label><label>Customer filename<input className="field" value={fileName} onChange={e=>setFileName(e.target.value)} placeholder="Zemen_Digital_AI_Kezero_v1.0.pdf"/></label></div><button className="btn" onClick={()=>void addExistingFile()}>Save existing file_id</button></details></div><div className="file-list">{detail.files.map(f=><article className={`file-row ${f.is_active?'file-row--active':''}`} key={f.id}><div className="file-icon"><Icon name="box"/></div><div><b>{f.file_name}</b><span>Version {f.version} · {f.mime_type||'file'} {f.size_bytes?`· ${(f.size_bytes/1024/1024).toFixed(1)} MB`:''}</span>{f.release_notes&&<p>{f.release_notes}</p>}</div><div><Status value={f.is_active?'active':'previous'}/>{!f.is_active&&<button className="btn btn--small" disabled={fileBusy} onClick={async()=>{setFileBusy(true);try{await api.activateProductFile(p!.id,f.id);await load()}finally{setFileBusy(false)}}}>Make active</button>}</div></article>)}</div>{!detail.files.length&&<Empty title="No delivery file" text="Digital files cannot publish until an active delivery file exists."/>}</div>}
  {tab==='salesman'&&<div className="editor-form"><div className="editor-section-head"><div><span>BOT SALESMAN</span><h3>Message matrix</h3></div><button className="btn btn--green" disabled={salesBusy} onClick={()=>void saveSales()}>{salesBusy?'Saving…':'Save salesman copy'}</button></div><div className="sales-filter"><label>Language<select className="field" value={salesLang} onChange={e=>setSalesLang(e.target.value as 'am'|'en')}><option value="am">Amharic</option><option value="en">English</option></select></label><label>Audience<select className="field" value={audience} onChange={e=>setAudience(e.target.value)}><option value="default">Default</option><option value="role:student">Student</option><option value="role:professional">Professional</option><option value="role:job_seeker">Job seeker</option><option value="role:business_owner">Business owner</option><option value="angle:beginner_confusion">Ad angle · beginner confusion</option><option value="obstacle:dont_know_what_to_ask">Obstacle · what to ask</option><option value="obstacle:poor_answers">Obstacle · poor answers</option></select></label></div><p className="helper-copy">Leave a field empty to use Zemen's built-in fallback. Saved copy immediately becomes available to the bot for this product + audience combination.</p><label>Hook / personalized pitch<textarea className="field textarea textarea--lg" value={hook} onChange={e=>setHook(e.target.value)} placeholder="HTML supported: <b>bold</b>, <i>italic</i>…"/></label><label>Preview / proof message<textarea className="field textarea textarea--lg" value={preview} onChange={e=>setPreview(e.target.value)}/></label><label>Objection response<textarea className="field textarea textarea--lg" value={objection} onChange={e=>setObjection(e.target.value)}/></label></div>}
  {tab==='upsells'&&<div className="editor-form"><div className="editor-section-head"><div><span>NEXT PRODUCT</span><h3>Upsells & recommendations</h3></div><button className="btn btn--green" disabled={relBusy} onClick={()=>void saveRels()}>{relBusy?'Saving…':'Save relationships'}</button></div><div className="relationship-add"><select className="field" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose another product…</option>{detail.catalog_choices.map(c=><option value={c.id} key={c.id}>{c.title} · {c.status}</option>)}</select><select className="field" value={relType} onChange={e=>setRelType(e.target.value as typeof relType)}><option value="upsell">Upsell</option><option value="cross_sell">Cross-sell</option><option value="next">Next recommended</option></select><button className="btn" onClick={addRel}>Add</button></div><div className="relationship-list">{rels.map((r,i)=><article key={r.id}><div><span>{String(i+1).padStart(2,'0')}</span><div><b>{r.target_title}</b><small>{r.target_slug} · {r.relationship_type.replaceAll('_',' ')}</small></div></div><button className="icon-btn" onClick={()=>setRels(rels.filter(x=>x.id!==r.id))}><Icon name="x"/></button></article>)}</div>{!rels.length&&<Empty title="No upsell path yet" text="Add the product customers should naturally see next."/>}</div>}
  </main></section></div>
}

export function ProductsView({items,reload}:{items:Product[];reload:()=>Promise<void>}){
  const[create,setCreate]=useState(false);const[selected,setSelected]=useState<string|null>(null);const[search,setSearch]=useState('');
  const shown=useMemo(()=>{const q=search.trim().toLowerCase();return q?items.filter(p=>`${p.title} ${p.slug} ${p.category||''}`.toLowerCase().includes(q)):items},[items,search])
  return <div className="page-stack"><SectionHead title="Products" subtitle="Catalog, store content, pricing, files and the bot salesman — one source of truth." action={<button className="btn btn--green" onClick={()=>setCreate(true)}>+ Create product</button>}/><div className="product-toolbar"><div className="searchbox"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…"/></div><div className="product-summary"><span>{items.filter(x=>x.status==='active').length} live</span><span>{items.length} total</span></div></div>{!shown.length?<Empty title="No products found"/>:<div className="product-control-grid">{shown.map(p=><button className="product-control product-control--button" key={p.id} onClick={()=>setSelected(p.id)}><div className="product-control__cover">{p.cover_url||p.cover?.startsWith('http')?<img src={p.cover_url||p.cover||''} alt=""/>:<div><span>Z</span></div>}<Status value={p.status}/></div><div className="product-control__body"><div className="product-card-head"><span className="micro">{p.slug}</span><span className="edit-hint">Edit <Icon name="chevron"/></span></div><h3>{p.title}</h3><div className="product-price"><strong>{money(p.regular_price_br)}</strong>{p.recovery_price_br&&<span>Recovery {money(p.recovery_price_br)}</span>}</div><div className="product-stats"><div><span>Sales</span><b>{p.sales_count}</b></div><div><span>Revenue</span><b>{money(p.revenue_br)}</b></div><div><span>Referral</span><b>{p.referral_enabled?`${p.referral_commission_percent}%`:'Off'}</b></div></div><div className="product-health"><span className={Number(p.active_file_count||0)>0?'ok':''}>{Number(p.active_file_count||0)>0?'✓':'•'} delivery</span><span className={p.cover_media_id?'ok':''}>{p.cover_media_id?'✓':'•'} cover</span>{p.discounts_enabled&&<span>Recovery on</span>}</div></div></button>)}</div>}{create&&<CreateProduct onClose={()=>setCreate(false)} onCreated={async d=>{setCreate(false);await reload();setSelected(d.product.id)}}/>}{selected&&<ProductEditor id={selected} onClose={()=>setSelected(null)} onChanged={reload}/>}</div>
}
