import { useState } from 'react'
import type { SettingsBundle } from '../api/types'
import { api } from '../api/client'
import { SectionHead, Status, dt, label } from '../components/UI'

function editableValue(v:unknown){return typeof v==='string'?v:JSON.stringify(v)}
function parseValue(v:string){const t=v.trim();if(t==='true')return true;if(t==='false')return false;if(/^[-+]?\d+(\.\d+)?$/.test(t))return Number(t);return v}

export function SettingsView({data,reload}:{data:SettingsBundle;reload:()=>void}){
  const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(data.settings.map(s=>[s.key,editableValue(s.value)])))
  const [admin,setAdmin]=useState({telegram_id:'',display_name:'',role:'operator'});const[busy,setBusy]=useState('')
  const save=async(key:string)=>{setBusy(key);try{await api.updateSafeSetting(key,parseValue(values[key]??''));reload()}catch(e){alert(e instanceof Error?e.message:'Could not save setting')}finally{setBusy('')}}
  const addAdmin=async()=>{setBusy('admin');try{await api.upsertAdmin({telegram_id:Number(admin.telegram_id),display_name:admin.display_name,role:admin.role});setAdmin({telegram_id:'',display_name:'',role:'operator'});reload()}catch(e){alert(e instanceof Error?e.message:'Could not save admin')}finally{setBusy('')}}
  return <div className="page-stack final-page"><div className="hero-head"><div><p className="eyebrow">CONTROL & GOVERNANCE</p><h1>Settings</h1><p>Safe business settings live here. Secrets stay in environment variables.</p></div></div>
    <article className="panel"><SectionHead title="Business settings" subtitle="Only allow-listed, non-secret settings are editable"/><div className="settings-list">{data.settings.map(s=><div className="setting-row" key={s.key}><div><strong>{label(s.key.replace('.',' · '))}</strong><span>{s.description||s.key}</span><small>{s.updated_by?`Updated by ${s.updated_by} · `:''}{dt(s.updated_at)}</small></div><input className="field" value={values[s.key]??editableValue(s.value)} onChange={e=>setValues({...values,[s.key]:e.target.value})}/><button className="btn btn--green" disabled={busy===s.key} onClick={()=>void save(s.key)}>{busy===s.key?'Saving…':'Save'}</button></div>)}</div></article>
    {data.role==='owner'&&<article className="panel"><SectionHead title="Administrators" subtitle="Owner-managed dashboard access. Viewer is read-only."/><div className="admin-create"><input className="field" inputMode="numeric" placeholder="Telegram ID" value={admin.telegram_id} onChange={e=>setAdmin({...admin,telegram_id:e.target.value.replace(/\D/g,'')})}/><input className="field" placeholder="Display name" value={admin.display_name} onChange={e=>setAdmin({...admin,display_name:e.target.value})}/><select className="field" value={admin.role} onChange={e=>setAdmin({...admin,role:e.target.value})}><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Admin</option><option value="owner">Owner</option></select><button className="btn btn--green" disabled={busy==='admin'||!admin.telegram_id||!admin.display_name.trim()} onClick={()=>void addAdmin()}>Save admin</button></div><div className="table-scroll"><table><thead><tr><th>Name</th><th>Telegram</th><th>Role</th><th>Status</th><th/></tr></thead><tbody>{data.admins.map(a=><tr key={a.id}><td><strong>{a.display_name}</strong></td><td>{a.telegram_id}</td><td>{label(a.role)}</td><td><Status value={a.is_active?'active':'disabled'}/></td><td><button className="btn" onClick={()=>void api.setAdminActive(a.id,!a.is_active).then(reload).catch(e=>alert(e instanceof Error?e.message:'Could not change admin'))}>{a.is_active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></article>}
    {data.audit.length>0&&<article className="panel"><SectionHead title="Recent audit trail" subtitle="Important operator changes"/><div className="audit-list">{data.audit.map(x=><div key={x.id}><span>{dt(x.created_at)}</span><strong>{label(x.action)}</strong><b>{x.admin_name||x.user_name||'System'}</b><small>{x.entity_type} · {x.entity_id}</small></div>)}</div></article>}
  </div>
}
